python3-pytest: add python3-setuptools runtime dep
Without this, pytest fails with missing a module

Traceback (most recent call last):
  File "/usr/bin/py.test", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'

https://github.com/void-linux/void-packages/commit/19175e62a2e94ad82d645ac0ecdf36ad8779a6ea