freepass: makedepends+=clang for libclang
- include error message
  - e.g.

```
Compiling libsodium-sys v0.1.0
error: failed to run custom build command for `libsodium-sys v0.1.0`

Caused by:
  process didn't exit successfully: `/builddir/freepass-*/cli/target/release/build/libsodium-sys-5f4234b264e9b6b0/build-script-build` (exit code: 101)
-- stdout
cargo:rerun-if-env-changed=SODIUM_LIB_DIR
cargo:rerun-if-env-changed=SODIUM_INC_DIR
cargo:rerun-if-env-changed=SODIUM_STATIC
cargo:rustc-link-search=native=/usr/include
cargo:rustc-link-lib=dylib=sodium

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any of [\'libclang.so\', \'libclang.so.*\', \'libclang-*.so\'], set the LIBCLANG_PATH environment variable to a path where one of these files can be found (skipped: [])"', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```