lnd: update to 0.14.1beta, mark broken.
    ...
    packagefile path/filepath=/host/gocache-glibc/a9/a9ebf35af8a7d849751c08b046ee0c734e6ef813523d89cccb91a2d9fc542900-d
    packagefile regexp=/host/gocache-glibc/34/34769aa22cdca012b30447b41bf3ecd5bc611815a1b5dc58bdba57daa100a221-d
    packagefile runtime=/host/gocache-glibc/59/5984d0bc27e7db61f2d7423f46559db706849a401de0529834dfb658178f2c5e-d
    packagefile strconv=/host/gocache-glibc/1f/1fef664511ab77d34751395f6b3193c475c42fae9a427b76dc047b204d0e51c8-d
    packagefile strings=/host/gocache-glibc/67/6788866770d1c9df78831b4ebf108e730cdc8927d8d6099f5dda0c04a38eca0e-d
    packagefile sync=/host/gocache-glibc/ed/ed81bfe60023380e22356fa79a9c4a1807547f3a62280a22876d3f62cce27154-d
    packagefile syscall=/host/gocache-glibc/bd/bd6a71e1aa4b135c5af7ea4bda1cf946a6bb888a699043e2018ca3a29f5cb1bb-d
    packagefile time=/host/gocache-glibc/e1/e12a3d036d01c50d03e7341f91bc13848f866b5440ab74bcd7a692d8880f691e-d
    packagefile unicode=/host/gocache-glibc/39/3958753c13394212e968897e5e85ce9da3adfa2054d0f425431cfab5598bf4ae-d
    EOF
    /usr/lib/go/pkg/tool/linux_amd64/compile -o $WORK/b519/_pkg_.a -trimpath "/builddir/lnd-v0.13.1-beta/_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli=>github.com/lightningnetwork/lnd/cmd/lncli;$WORK/b519=>" -p main -complete -buildid sTnWLr-LHzK6MNVBUpHw/sTnWLr-LHzK6MNVBUpHw -goversion go1.17.5 -importcfg $WORK/b519/importcfg -pack -c=4 ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/arg_parse.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/autopilotrpc_default.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/cmd_custom.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/cmd_import_mission_control.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/cmd_invoice.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/cmd_macaroon.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/cmd_mission_control.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/cmd_open_channel.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/cmd_payments.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/cmd_profile.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/cmd_state.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/cmd_update_chan_status.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/cmd_version.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/cmd_walletunlocker.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/commands.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/invoicesrpc_default.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/macaroon_jar.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/main.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/profile.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/routerrpc.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/types.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/walletrpc_default.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/walletrpc_types.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/watchtower_default.go ./_build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/wtclient.go
    # github.com/lightningnetwork/lnd/cmd/lncli
    _build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/cmd_custom.go:14:17: cannot use cli.StringFlag{...} (type cli.StringFlag) as type cli.Flag in slice literal:
            cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
    _build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/cmd_custom.go:17:17: cannot use cli.Uint64Flag{...} (type cli.Uint64Flag) as type cli.Flag in slice literal:
            cli.Uint64Flag does not implement cli.Flag (Apply method has pointer receiver)
    _build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/cmd_custom.go:20:17: cannot use cli.StringFlag{...} (type cli.StringFlag) as type cli.Flag in slice literal:
            cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
    _build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/cmd_import_mission_control.go:23:15: cannot use cli.BoolFlag{...} (type cli.BoolFlag) as type cli.Flag in slice literal:
            cli.BoolFlag does not implement cli.Flag (Apply method has pointer receiver)
    _build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/cmd_invoice.go:24:17: cannot use cli.StringFlag{...} (type cli.StringFlag) as type cli.Flag in slice literal:
            cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
    _build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/cmd_invoice.go:29:17: cannot use cli.StringFlag{...} (type cli.StringFlag) as type cli.Flag in slice literal:
            cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
    _build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/cmd_invoice.go:36:16: cannot use cli.Int64Flag{...} (type cli.Int64Flag) as type cli.Flag in slice literal:
            cli.Int64Flag does not implement cli.Flag (Apply method has pointer receiver)
    _build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/cmd_invoice.go:40:16: cannot use cli.Int64Flag{...} (type cli.Int64Flag) as type cli.Flag in slice literal:
            cli.Int64Flag does not implement cli.Flag (Apply method has pointer receiver)
    _build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/cmd_invoice.go:44:17: cannot use cli.StringFlag{...} (type cli.StringFlag) as type cli.Flag in slice literal:
            cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
    _build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/cmd_invoice.go:52:17: cannot use cli.StringFlag{...} (type cli.StringFlag) as type cli.Flag in slice literal:
            cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
    _build-lnd-xbps/src/github.com/lightningnetwork/lnd/cmd/lncli/cmd_invoice.go:52:17: too many errors
    => ERROR: lnd-0.13.1beta_1: do_build: 'go get -p "$XBPS_MAKEJOBS" -x -tags "${go_build_tags}" -ldflags "${go_ldflags}" ${go_package}' exited with 2
    => ERROR:   in do_build() at common/build-style/go.sh:39