Revert "libucontext: update to 0.13.1"
This reverts commit b6bdb48a249e96e0c2ddba68e8e63076b225708f.

@pullmoll

Newer libucontext seems to break ABI, which results in lots of
things suddenly failing to build, e.g.

/usr/bin/ld: /lib64/libunwind.so.8: undefined reference to `__setcontext'
/usr/bin/ld: /usr/lib/libgstreamer-1.0.so: undefined reference to `__getcontext'
collect2: error: ld returned 1 exit status

I suspect because of

https://github.com/kaniini/libucontext/commit/99ed5bbe12cb04c8918514a9f32e4908e06b423d

https://github.com/void-linux/void-packages/commit/be4cdeb83a33b9fc4a2b258f9041843624c5553a