Fix CI since github no longer accepts git:// protocol
As of today, everything fails on CI with:

```
Run common/travis/fetch_upstream.sh
Fetching upstream...
fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
Error: Process completed with exit code 128.
```

Switching `git://` to `https://` should fix this.

https://github.com/void-linux/void-packages/commit/92720ddd33b243ef1f7dd87575a7eea6a8f95513